name: Build and Deploy NuGet Packages
on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  
defaults:
  run:
    shell: pwsh
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x' # Update to the appropriate .NET version

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build and Publish NuGet Packages
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} /p:VersionSuffix=$GITHUB_REF_NAME
      # GITHUB_REF_NAME is the tag name

    - name: Publish NuGet package
      run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg))
          {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
