name: Build and Deploy NuGet Packages
on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x' # Update to the appropriate .NET version

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build and Publish NuGet Packages
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release --output ./nupkg /p:VersionSuffix=$GITHUB_REF_NAME
      # GITHUB_REF_NAME is the tag name

    - name: Deploy NuGet Packages
      uses: nuget/nuget-push@v2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        source: './nupkg/*.nupkg'
